# Generated by Django 4.1 on 2022-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='desc',
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(default='Vihiga', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='form',
            field=models.CharField(default='Form one(1)', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='kcpe_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='kcpe_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=12345678, max_length=25),
        ),
    ]
