# Generated by Django 4.1 on 2022-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0003_alter_student_form_alter_student_kcpe_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='form',
            field=models.CharField(choices=[('Form One(1)', 'Form One(1)'), ('Form Two(2)', 'Form Two(2)'), ('Form Three(3)', 'Form Three(3)'), ('Form Four(4)', 'Form Four(4)')], default='Form One(1)', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=10),
        ),
    ]
