# Generated by Django 4.1 on 2022-09-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0005_alter_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='kcpe_years',
            new_name='kcpe_year',
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
